server:
  port: 9090
spring:
  application:
    name: consumer-service


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka