server:
  port: 8000

spring:
  application:
    name: server-demo

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        SpringBootActuator监控暴露所有接口
  endpoint:
     health:
          show-details: ALWAYS