server:
  port: 8888
spring:
  application:
    name: config-local-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"