server:
  port: 20000

test:
  uri: http://127.0.0.1:9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://www.baidu.com
          predicates:
          - Path=/baidu
        - id: host_route
          uri: http://localhost:9090
          predicates:
          - Path=/**

