server:
  port: 7000
spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka