server:
  port: 10000

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8080/eureka

zuul:
  routes:
    provider:
      path: /**
      serviceId: consumer-service
